name = "gen-seq"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["GenSeq"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.20.1"

[[lean_lib]]
name = "GenSeq"
