name: Lean Action CI

on:
  push:
    branches:
      - main # Trigger on pushes to the default branch
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leanprover/lean-action@v1
