value: ONE
| TWO
| X
| Y

ONE: "1"
TWO: "2"
X: "x"
Y: "y"
PLUS: "+"
MINUS: "-"
TIMES: "*"
DIV: "div"
MOD: "mod"

sum: value PLUS value
diff: value MINUS value
times: value TIMES value
div: value DIV value
mod: value MOD value

expr: value
| sum 
| diff
| times 
| div 
| mod 


%import common.WS
%ignore WS
